# Generated by Django 6.0.7 on 2026-07-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='course',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='due_date',
        ),
        migrations.AddField(
            model_name='recipient',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
